name: Vite Frontend - Build and Deploy to GitHub Pages

on:
  # Disabled until frontend project is created
  # push:
  #   branches: [ "main", "frontend" ]
  #   paths:
  #     - 'member2_frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: member2_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: member2_frontend/package-lock.json

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: |
          if [ ! -f package.json ]; then
            echo "No package.json found - skipping frontend build"
            exit 0
          fi
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Build
        env:
          # Set Vite base path to "/<repo>/" for GitHub Pages
          VITE_BASE: "/${{ github.event.repository.name }}/"
        run: |
          if [ ! -f package.json ]; then
            echo "No package.json found - skipping build"
            mkdir -p dist
            echo "<html><body><h1>Frontend placeholder</h1></body></html>" > dist/index.html
          else
            npm run build
          fi

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: member2_frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
